INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'NA','NAPOLI');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BA','BARI');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BO','BOLOGNA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CA','CAGLIARI');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CT','CATANIA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FI','FIRENZE');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'GE','GENOVA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'ME','MESSINA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MI','MILANO');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PA','PALERMO');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RC','REGGIO CALABRIA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RM','ROMA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TO','TORINO');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VE','VENEZIA');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AG','Agrigento');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AL', 'Alessandria');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AN', 'Ancona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AR', 'Arezzo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AP', 'Ascoli Piceno');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AT', 'Asti');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AV', 'Avellino');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BT', 'Barletta-Andria-Trani');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BL', 'Belluno');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BN', 'Benevento');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BG', 'Bergamo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BI', 'Biella');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BZ', 'Bolzano');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BS', 'Brescia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'BR', 'Brindisi');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CL', 'Caltanissetta');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CB', 'Campobasso');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CE', 'Caserta');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CZ', 'Catanzaro');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CH', 'Chieti');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CO', 'Como');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CS', 'Cosenza');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CR', 'Cremona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'KR', 'Crotone');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'CN', 'Cuneo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'EN', 'Enna');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FM', 'Fermo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FE', 'Ferrara');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FG', 'Foggia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FC', 'Forlì-Cesena');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'FR', 'Frosinone');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'GO', 'Gorizia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'GR', 'Grosseto');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'IM', 'Imperia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'IS', 'Isernia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'AQ', 'L\'Aquila');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SP', 'La Spezia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LT', 'Latina');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LE', 'Lecce');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LC', 'Lecco');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LI', 'Livorno');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LO', 'Lodi');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'LU', 'Lucca');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MC', 'Macerata');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MN', 'Mantova');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MS', 'Massa-Carrara');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MT', 'Matera');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MO', 'Modena');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'MB', 'Monza e Brianza');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'NO', 'Novara');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'NU', 'Nuoro');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'OR', 'Oristano');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PD', 'Padova');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PR', 'Parma');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PV', 'Pavia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PG', 'Perugia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PU', 'Pesaro e Urbino');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PE', 'Pescara');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PC', 'Piacenza');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PI', 'Pisa');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PT', 'Pistoia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PN', 'Pordenone');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PZ', 'Potenza');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'PO', 'Prato');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RG', 'Ragusa');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RA', 'Ravenna');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RE', 'Reggio Emilia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RI', 'Rieti');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RN', 'Rimini');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'RO', 'Rovigo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SA', 'Salerno');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SS', 'Sassari');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SV', 'Savona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SI', 'Siena');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SR', 'Siracusa');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SO', 'Sondrio');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'SU', 'Sud Sardegna');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TA', 'Taranto');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TE', 'Teramo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TR', 'Terni');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TP', 'Trapani');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TN', 'Trento');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TV', 'Treviso');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'TS', 'Trieste');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'UD', 'Udine');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VA', 'Varese');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VB', 'Verbano-Cusio-Ossola');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VC', 'Vercelli');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VR', 'Verona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VV', 'Vibo Valentia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VI', 'Vicenza');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (105,'VT', 'Viterbo');
INSERT INTO `geo_zones`(`geo_zone_name`, `geo_zone_description`, `date_added`) VALUES ('Italia','Tasse Italiane',NOW());
INSERT INTO `zones_to_geo_zones`(`zone_country_id`, `geo_zone_id`, `date_added`) VALUES (105,(SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('22','Aliquota IVA ordinaria',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('10','Aliquota IVA ridotta',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('5','Aliquota IVA ridotta speciale',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('4','Aliquota IVA minima',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N1','Fuori campo IVA art. 15 del DPR 633/72',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N2-2.3a','Fuori campo IVA art. 2 comma 3 lettera a del DPR 633/72',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N2.2','Operazione fuori campo IVA',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N3.1','Non imponibili art 8 e 9',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N4-10','Esente Articolo 10 del DPR 633/72',NOW());
INSERT INTO `tax_class`(`tax_class_title`, `tax_class_description`, `date_added`) VALUES ('N6.7','Inversione Contabile',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = '22'),'22','Aliquota 22%',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = '10'),'10','Aliquota 10%',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = '5'),'5','Aliquota 5%',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = '4'),'4','Aliquota 4%',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N1'),'0','Natura N1',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N2-2.3a'),'0','Natura N2 articolo 2.3a',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N2.2'),'0','Natura N2.2',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N3.1'),'0','Natura N3.1',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N4-10'),'0','Natura N4',NOW());
INSERT INTO `tax_rates`(`tax_zone_id`, `tax_class_id`, `tax_rate`, `tax_description`, `date_added`) VALUES ((SELECT MAX(geo_zone_id) FROM geo_zones WHERE geo_zone_name = 'Italia' AND geo_zone_description = 'Tasse Italiane'),(SELECT MAX(tax_class_id) FROM tax_class WHERE tax_class_title = 'N6.7'),'0','Natura N6.7',NOW());